### ISSUE TITLE
Assert: div expected to contain text Logout

### ISSUE THREAD

**Issue by jabir366** [shivamguys/irctc-cypress-automation#14]
while running the text with manual captcha enabled. this happened after entering the captcha. the error was
![image](https://github.com/shivamguys/irctc-cypress-automation/assets/17222278/9b199aa3-8a96-40c4-b654-c76b082b299a)

**Comment by shivamguys** [comment]
been busy for the past few months ,,, I will sort all things out gradually.....
Thanks for testing this and letting me know

**Comment by drtechie** [comment]
@jabir366 there seems to be no error in the screenshot.
The text shows successful assertion of logout text (which means you are logged in successfully). 
The script has gone ahead and typed CLT station code.
My guess is that the station code results didn't show up correctly and the click didn't happen.
Is this issue persisting?

**Comment by shivamguys** [comment]
Sorted....
