### ISSUE TITLE
Need to handle "Booking has not started" even after its talkal time

### ISSUE THREAD

**Issue by jabir366** [shivamguys/irctc-cypress-automation#16]
Sometimes the script fails to handle the case of "Booking has not started" message coming from IRCTC website after 10.00 am or 11.am in such cases we can sleep for some time or check whether the `book` button is active and click on it while it is active. right now it is not handled

**Comment by shivamguys** [comment]
i guess @drtechie  pushed a commit and i merged it would solve this issue.........

**Comment by drtechie** [comment]
#15

**Comment by shivamguys** [comment]
Fixed in #23
