### ISSUE TITLE
Setting up google credentials

### ISSUE THREAD

**Issue by VidhyaVarshanyJS** [shivamguys/irctc-cypress-automation#2]
How can I get the json path of the google credentials?

**Comment by drtechie** [comment]
Download the service account JSON from the Google console and set the environment variable.

`export GOOGLE_APPLICATION_CREDENTIALS=/Users/path/to/account.json`

**Comment by shivamguys** [comment]
@VidhyaVarshanyJS  are you able to use  now ?

**Comment by VidhyaVarshanyJS** [comment]
I couldn't able to use vision api  as I couldn't able to add billing account..

**Comment by VidhyaVarshanyJS** [comment]
Is there any way that I could make use of this, ?

**Comment by shivamguys** [comment]
Dont you have any visa card having less than 50₹ and just sign up

**Comment by shivamguys** [comment]
What's the problem its showing while adding billing account

**Comment by VidhyaVarshanyJS** [comment]
I don't have one that's the problem.I actually need to make this work..

**Comment by VidhyaVarshanyJS** [comment]
I have only rupay card

**Comment by shivamguys** [comment]
Ohh in that case you will need one.
By the way Paytm Payments Bank provide visa card in case you have paytm
account

**Comment by VidhyaVarshanyJS** [comment]
Paytm is also has the rupay card.is there any way I could make this working for me without Google auth credentials?

**Comment by shivamguys** [comment]
By the way where do you reside?
Try opening an account in Niyox Search in Play Store they also provide
instant virtual visa card free of cost. Zero Balance Account Opening

**Comment by VidhyaVarshanyJS** [comment]
I reside in India...
Does that instant virtual visa card creation needs any of my bank account details?

**Comment by VidhyaVarshanyJS** [comment]
Niyox is upgraded and asks me to wait until it notifies

**Comment by VidhyaVarshanyJS** [comment]
I have tried the possible ways i couldn't make up the billing account in gcp

**Comment by shivamguys** [comment]
Ohh Is it...
Let me think what i can do for you to make this work.
I guess I have to give you some creds from some dummy email with billing
set up in that.

**Comment by VidhyaVarshanyJS** [comment]
did you find the solution ?

**Comment by shivamguys** [comment]
Bro busy with these office things.
Will provide you creds soon

**Comment by shivamguys** [comment]
sorry @VidhyaVarshanyJS  to call you bro, I didn't know I was replying through emails...

**Comment by shivamguys** [comment]
I tried setting up my other visa account for sharing purposes but unfortunately, I can't as it needs to be e-mandate and I have only one visa card that supports that, @VidhyaVarshanyJS 

> Attention Customers from India: As of October 1st, due to regulatory changes by the Reserve Bank of India, we will not be able to charge your card for recurring payments if you have not set up an e-mandate or if the transaction is above 5000 INR. If your payments are being declined, Billing administrators will have to log into their Payments account and manually reauthorize the payments.

**Comment by VidhyaVarshanyJS** [comment]
Then, how can I make use of this?

**Comment by drtechie** [comment]
@VidhyaVarshanyJS get a VISA card from one of your friends? If you use Googlr Cloud services judiciously, you will never get charged. 

PS: IMHO, this issue doesn't pertain to this repo. It's how Google billing operates. ¯\_(ツ)_/¯

**Comment by VidhyaVarshanyJS** [comment]
Tbh, I can't ask my friend the visa card is there any other way to get the visa card

**Comment by shivamguys** [comment]
share your email @VidhyaVarshanyJS  i have created keys for you...
remember to use it carefully don't share that.....

**Comment by shivamguys** [comment]
very weird I can find every detail in your profile but not your email ... @VidhyaVarshanyJS

**Comment by VidhyaVarshanyJS** [comment]
vidhyavarshany03@gmail.com

**Comment by VidhyaVarshanyJS** [comment]
> share your email @VidhyaVarshanyJS i have created keys for you... remember to use it carefully don't share that.....

Sure

**Comment by shivamguys** [comment]
Done....

**Comment by shivamguys** [comment]
This has been resolved now....

**Comment by VidhyaVarshanyJS** [comment]
Hey , shall we connect now?
