### ISSUE TITLE
Error While inputting the Passenger name

### ISSUE THREAD

**Issue by siddhu2310** [shivamguys/irctc-cypress-automation#20]
I 'm testing for  with manaul captcha and Tatkal False,
Evrything is going  fine, while on the Pasenger Details it  stop there.

![irctc error](https://github.com/shivamguys/irctc-cypress-automation/assets/91126369/e465246d-6e9f-45e3-ac10-cf0d959be2e2)

`Console Log:`

```
Uncaught ReferenceError: irctc is not defined
    <anonymous> https://cdn.jsdelivr.net/gh/corover/assets@t60/askdisha-bucket/chatbot_IRCTC_V2.js?1705573011708:1781
    invokeTask https://www.irctc.co.in/nget/polyfills-es2015.a8f29f173d5f450a625f.js:1
    runTask https://www.irctc.co.in/nget/polyfills-es2015.a8f29f173d5f450a625f.js:1
    invokeTask https://www.irctc.co.in/nget/polyfills-es2015.a8f29f173d5f450a625f.js:1
    invoke https://www.irctc.co.in/nget/polyfills-es2015.a8f29f173d5f450a625f.js:1
    0 https://www.irctc.co.in/nget/polyfills-es2015.a8f29f173d5f450a625f.js:1
    o https://www.irctc.co.in/nget/train-search:3
    i https://www.irctc.co.in/nget/train-search:3
153 chatbot_IRCTC_V2.js:1781:9

```

**Comment by shivamguys** [comment]
I just checked its working....

![image](https://github.com/shivamguys/irctc-cypress-automation/assets/25263989/4379c1b4-ce3c-4535-8c33-14256fe4581b)

**Comment by siddhu2310** [comment]
Is there nay issue with Windows Machine ?

**Comment by shivamguys** [comment]
what's your passenger array look like can you share that...
and are you on the latest code....?

**Comment by shivamguys** [comment]
leave that take mine 
enjoy :-)


[abiding-cistern-247021-995e4c1e13e5.json](https://github.com/shivamguys/irctc-cypress-automation/files/13978298/abiding-cistern-247021-995e4c1e13e5.json)

**Comment by siddhu2310** [comment]
Thanks for sharing the API KEY.

```set GOOGLE_APPLICATION_CREDENTIALS="D:\irctc\irctc-cypress-automation\google_api\abiding-cistern-247021-995e4c1e13e5.json"

python app.py```

Is this correct Methods to add the  API or just needs to add path alone.

**Comment by shivamguys** [comment]
Before that export the file path also.
That i gave you the json file


See in the readme it looks like export...

**Comment by siddhu2310** [comment]
Sorry, I missed some of the text in the previous comment:

This is my question, Whether I need to add full path with file name or just only file path

***cmd code:***
```
::only PATH
set GOOGLE_APPLICATION_CREDENTIALS="C:\Users\Siddharth\Downloads\irctc-cypress-automation-main\irctc-captcha-solve-server\api"

::full PATH with file name
set GOOGLE_APPLICATION_CREDENTIALS="C:\Users\Siddharth\Downloads\irctc-cypress-automation-main\irctc-captcha-solve-server\api\abiding-cistern-247021-995e4c1e13e5.json"

::Run Flask Server
python app.py

```

**Comment by shivamguys** [comment]
Full path including that json

**Comment by siddhu2310** [comment]
I have set env , even it is showing an error

```
Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.

```

**Comment by siddhu2310** [comment]
It's okay ,  i will use Manual Captcha .
