### ISSUE TITLE
[Feature Request] Payment Method E-Wallet

### ISSUE THREAD

**Issue by siddhu2310** [shivamguys/irctc-cypress-automation#21]
Could you please add E-wallet payment methods as well?
Since some time, redirecting Paytm Payment page and coming back is problem.

**Comment by shivamguys** [comment]
I will advise in that case just reload the browser with cntrl + r .
It happened with me and i refreshed the browser and that worked..

**Comment by siddhu2310** [comment]
When I press Ctrl + R , it reloads from the beginning.

**Comment by shivamguys** [comment]
I think the majority of people use QR Payment these days and an E-Wallet would not be feasible for everyone and much config would be needed for everyone else to opt for QR switching from E-wallet
