### ISSUE TITLE
[Issue] Passenger name Update page stopped

### ISSUE THREAD

**Issue by siddhu2310** [shivamguys/irctc-cypress-automation#22]
When I tried before the tatkal timing , the passenger name filling was good, During the tatkal time the name are not filled.
So I entered names manually when the payment was done with paytm  , the page should show booked or not booked , but it was redirected previous page.

Kindly check the script again.

**Comment by shivamguys** [comment]
are you saying irctc popped up with something last booking something....
I booked one tatkal SL ticket yesterday everything worked like a charm....

**Comment by shivamguys** [comment]
Fixed in #23
