### ISSUE TITLE
Unable to perform booking if opened just few seconds after tatkal time 

### ISSUE THREAD

**Issue by shivamguys** [shivamguys/irctc-cypress-automation#23]
Behavior was stuck in div `cy.get('div.h_head1', { timeout: 300000 }).should('include.text', exactTimeToOpen)` waiting for 11:00 but time has already elapsed in that case.

Also target time was always returning `false` `M {$L: 'en', $u: undefined, $d: Invalid Date, $y: NaN, $M: NaN, …}`

@drtechie

**Comment by siddhu2310** [comment]
Now Working like a charm,
Previously I said Auto Captcha is not working, Now that's too working.

OS: Windows 11

Thank you for the effort @shivamguys  @drtechie

**Comment by shivamguys** [comment]
> Now Working like a charm, Previously I said Auto Captcha is not working, Now that's too working.
> 
> OS: Windows 11
> 
> Thank you for the effort @shivamguys @drtechie

Thanks 👍

**Comment by siddhu2310** [comment]
@shivamguys , During Tatkal time, did you enable option **Book only if confirmed berths allotted**

**Comment by siddhu2310** [comment]
@shivamguys  Enable that option for Tatkal, Since if seats are not available it will go WL.

**Comment by shivamguys** [comment]
Confirmation Prompt clicking added this is in case you have opted for no food in vande bharat and irctc shows suggesting you to opt for it.....

@drtechie @siddhu2310 

![image](https://github.com/shivamguys/irctc-cypress-automation/assets/25263989/b8b8d76a-bdad-46bb-b360-1e079a770ca5)

Pull out the latest commit for this........

**Comment by nssivashankar** [comment]
> Now Working like a charm, Previously I said Auto Captcha is not working, Now that's too working.
> 
> OS: Windows 11
> 
> Thank you for the effort @shivamguys @drtechie

how auto captcha works in windows bro can you help me
