### ISSUE TITLE
captcha_error

### ISSUE THREAD

**Issue by tamilsandro** [shivamguys/irctc-cypress-automation#24]
while running the code i get cy.request() failed trying to load:  and  Error: connect ECONNREFUSED 127.0.0.1:5000 
As you said -- BASE_URL is the local python server which you will run is responsible for filling captchas for you.
can you guide me how to find BASE_URL

**Comment by shivamguys** [comment]
Did you run the python server?

```
cd irctc-cypress-automation/irctc-captcha-solve-server
pip3 install -r requirements.txt
export GOOGLE_APPLICATION_CREDENTIALS="your credentials file path goes here please change this............"
python3 app.py
```

**Comment by tamilsandro** [comment]
![Screenshot 2024-02-18 225221](https://github.com/shivamguys/irctc-cypress-automation/assets/160408606/eff965d4-d7d2-49db-93cb-b9a8c570140d)
![Screenshot 2024-02-18 225305](https://github.com/shivamguys/irctc-cypress-automation/assets/160408606/e807bdc2-4b82-4310-8f54-77ffbcf51664)

ya added and cross checked but still same issue did i miss anything

**Comment by tamilsandro** [comment]
added all those python dependency's only problem is captcha except that all running fine

**Comment by shivamguys** [comment]
You can reference https://github.com/shivamguys/irctc-cypress-automation/issues/10
