### ISSUE TITLE
Empty window is opened while running "npx cypress open"

### ISSUE THREAD

**Issue by rsksh** [shivamguys/irctc-cypress-automation#25]
Empty window is opened while running "npx cypress open"

I am using a debian 12 (bookworm) machine vm in vmware and everything is set up. 
But after running the  _npx cypress open_ a window is opened. But it is completely blank.
Also in the running terminal there is no error.

![2024-02-20 16_46_24-Debian 11 x 64-bit osbox - VMware Workstation](https://github.com/shivamguys/irctc-cypress-automation/assets/9404952/e740e7a0-68d5-4df2-b262-36d72df2f3e9)

**Comment by shivamguys** [comment]
Do you have any browser installed in your os?

**Comment by rsksh** [comment]
Yes Firefox is there. 
I was able to fix this issue by running "xhost +" command. 
So closing this bug.
