### ISSUE TITLE
Continued to refresh QR code after payment done

### ISSUE THREAD

**Issue by rockydares** [shivamguys/irctc-cypress-automation#31]
Payment was successful by QR code but still it was refreshing new QR code. Waited for a minute then I closed cypress. Ticket not booked it says.

```
(other)POST 200 https://securegw.paytm.in/theia/processTransaction?orderid=1000048842xxxxx
payment
(new url)https://securegw.paytm.in/theia/processTransaction?orderid=1000048842xxxxx
logObject{10}
(uncaught exception)TypeError: Cannot read properties of null (reading 'postMessage')
```

**Comment by shivamguys** [comment]
Ticket not booked it says. By IRCTC ? 
Might be paytm would not have received callback after payment done

**Comment by shivamguys** [comment]
the code has nothing to do after payment is done.
Paytm would not have received the callback as ``` (uncaught exception)TypeError: Cannot read properties of null (reading 'postMessage') ``` is Paytm response object checking for transaction status.
There might be something wrong on Paytm's side for that particular TXN.
@rockydares

**Comment by shivamguys** [comment]
Stale Closing This.....
