### ISSUE TITLE
Auto fill Credentials

### ISSUE THREAD

**Issue by MasterSJit** [shivamguys/irctc-cypress-automation#33]
**Describe the bug**

The username and password is **_not filling automatically_**, i tried several times but it's not working

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 123.0.6312.107

**Comment by shivamguys** [comment]
Can you please try with the latest commit and report if problem exists?
@MasterSJit

**Comment by shivamguys** [comment]
Any updates @MasterSJit

**Comment by MasterSJit** [comment]
> Can you please try with the latest commit and report if problem exists? @MasterSJit

I tried in latest commit on that day you just commit and after 28min i tried. Let me check it again and i will let you know

**Comment by shivamguys** [comment]
K

**Comment by MasterSJit** [comment]
The Cypress not even lunching now
you can see here cypress icon on dock but not showing ui and in terminal also you can see **website fetch completed** log is showing.
<img width="1018" alt="image" src="https://github.com/shivamguys/irctc-cypress-automation/assets/20654014/6eeb8967-a572-4d50-9b32-5b5c51591a91">

**Comment by ampliads** [comment]
**Desciption of Bug:**
I have encountered the same issue.

Environment:
Win10x64
Browser: Chrome  

Screen Recording can be found at : https://filebin.net/rmyx7bc0tnyvd7qi

**Comment by shivamguys** [comment]
### Please Pull The Latest Code Now....  @MasterSJit  @ampliads 

This has been addressed because of the naming issue earlier all were in lower case... Now CAPITALIZED

**Old**
```
    "username": "yourusername",
    "password": "yourpassword",
```

**Now After Fixing**
```
    "USERNAME": "yourusername",
    "PASSWORD": "yourpassword",
```
