### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by bharat247online** [shivamguys/irctc-cypress-automation#36]
I am getting errors    . I am running it on github codespace .
![image](https://github.com/shivamguys/irctc-cypress-automation/assets/166898543/570af85f-8e19-407a-81db-31798df19eb2)
![image](https://github.com/shivamguys/irctc-cypress-automation/assets/166898543/8994db74-67df-4a36-9d94-17996291cb80)
@shivamguys

**Comment by shivamguys** [comment]
Have you tried to fork it and run in GitHub Actions?

@bharat247online

**Comment by shivamguys** [comment]
@bharat247online  ?

**Comment by shivamguys** [comment]
@bharat247online  Read this  https://github.com/shivamguys/irctc-cypress-automation/discussions/38

**Comment by shivamguys** [comment]
Did you get this working on your system?
@bharat247online

**Comment by bharat247online** [comment]
Yes but again the new issue is that whenever I try with more than one
passenger , in such case it's unable to parse the first passenger. Rest for
one passenger it's working fine.

Regards

**Comment by shivamguys** [comment]
unable to parse means is it throwing error for that file passenger_data.json ? @bharat247online

**Comment by shivamguys** [comment]
please check how to define more than one passenger in passenger_data.json see the readme for that, I guess you may have missed commas.

**Comment by bharat247online** [comment]
No it's not the error thrown by Cyprus's but from irctc because the first
passenger name was not given and rest field for the first passenger were
filled.

I have given two passenger detail .

Also I want to highlight that if I login at 9:59:30 then also due to
multiple check for tatkal window opening time it logs out.so the pinging
rate should be less. Because in tatkal time if there are much ping from
same ip then it's get logout.

By the way please feel free to wp me on 8674830184.Bar bar mail likhne
bahut dikat hai bhai.

**Comment by shivamguys** [comment]
its works fine for more than one passenger and for others as well don't know whats wrong in your system @bharat247online  I have seen many users run its working fine for them also... 

Sure will ping you on whatsapp as well
