### ISSUE TITLE
How i can use it in Windows, you have not given guidelines for windows

### ISSUE THREAD

**Issue by ujjwalbharadwaj** [shivamguys/irctc-cypress-automation#37]
![image](https://github.com/shivamguys/irctc-cypress-automation/assets/79165874/dd0b43d4-8cc4-42f0-ad0b-c7ed9a2c0e51)

**Comment by shivamguys** [comment]
In that case you can use Github to fork and run your code through github....

To be frank I am not a windows user and haven't tested this on windows ...

**Comment by ujjwalbharadwaj** [comment]
Thank you for replying but I think most of the people uses windows based machine so you should try ones this on window so more people will get benefited from your tool.

**Comment by shivamguys** [comment]
@ujjwalbharadwaj   Did You tried to fork this and run on your own Github Profile Using the action tab ?

If you don't know i will prepare a guide for all of you ?

**Comment by shivamguys** [comment]
And Please Favourite this ⭐. If you find this helpful.
Much appreciated @ujjwalbharadwaj

**Comment by shivamguys** [comment]
Refer This To Run https://www.canva.com/design/DAGCmLdOM0g/5K21SNKKKZZMM4428K9wUw/view?utm_content=DAGCmLdOM0g&utm_campaign=designshare&utm_medium=link&utm_source=editor

@ujjwalbharadwaj

**Comment by ujjwalbharadwaj** [comment]
Its not working on github using these steps and in my local machine its giving an Os error.

**Comment by siddhu2310** [comment]
@ujjwalbharadwaj 

Install Node JS,
and Python 

follow below steps

open cmd  and go to the folder path D:\irctc_v2\irctc-cypress-automation-main
**pip install -r irctc-captcha-solver/requirements.txt**
**npm update**

go to Support/command.js
change the python3 to python

then  run 
**npx cypress run --headed --no-exit**
