### ISSUE TITLE
getting this error when i try to book tatkal. i dont know whats this error means and how to resolve it.

### ISSUE THREAD

**Issue by jainuls** [shivamguys/irctc-cypress-automation#43]
![image](https://github.com/shivamguys/irctc-cypress-automation/assets/92950109/cacea1a2-a1a5-42b0-a4b4-77882ef32c78)

**Comment by jainuls** [comment]
this also comes in general reservation

**Comment by shivamguys** [comment]
try clearing your **production** folder follow below steps..

![image](https://github.com/shivamguys/irctc-cypress-automation/assets/25263989/a810f2db-193c-4405-88ab-bc8dcde12fbd)

Go to **developer tools**

then Go to **view app data**

Delete everything in that folder.....

![image](https://github.com/shivamguys/irctc-cypress-automation/assets/25263989/b0e94eaf-d281-4114-ae9a-bf6fac6c56b9)



@jainuls 

Follow and inform me if that worked....

**Comment by jainuls** [comment]
@shivamguys nope, still facing the same issue but only during the tatkal time. other times its working fine.

**Comment by shivamguys** [comment]
@jainuls  You are trying in your system right ?
During tatkal time.....


I am aware of this bug in workflow during tatkal time but not sure if it exists running in your system as well during tatkal time

**Comment by shivamguys** [comment]
Hope this has been addressed 
Closing now
