### ISSUE TITLE
Received a error when captcha was sloved

### ISSUE THREAD

**Issue by Tulsipada** [shivamguys/irctc-cypress-automation#45]
**Describe the bug**
Python install properly even `python irctc-captcha-solver/app.py ""` this comment was run successfully .
i got a error 

**Screenshots**
<img width="1440" alt="Screenshot 2024-04-30 at 7 26 07 AM" src="https://github.com/shivamguys/irctc-cypress-automation/assets/36180690/20c44df4-891a-4a4c-9f0f-42534f4e7e99">
![Uploading Screenshot 2024-04-30 at 7.26.38 AM.png…]()

**Desktop (please complete the following information):**

**Additional context**
can you explain about this issue

**Comment by shivamguys** [comment]
@Tulsipada  can you change all `python` to `python3` in `cypress/support/commands.js` file and then check...

**Comment by Tulsipada** [comment]
Same issue.

**Comment by shivamguys** [comment]
https://stackoverflow.com/questions/56252299/mac-os-x-modulenotfounderror-no-module-named-numpy

@Tulsipada

**Comment by Tulsipada** [comment]
@shivamguys thank you! its working now using python3

**Comment by shivamguys** [comment]
Your welcome 😁...
@Tulsipada 

Do share it so that it reaches others
