### ISSUE TITLE
Failed to fill username and password

### ISSUE THREAD

**Issue by jabir366** [shivamguys/irctc-cypress-automation#46]
**Describe the bug**
The script failed to input the username and password , there was an ad showing near to the username and password textboxes. tried running it multiple times, got the same issue 

branch : `main` 
commit id : `e80d3d4f4bf47db10b9d29e4ea237f4b41c94f6e`

**If you are encountering any error please run this**
```npx cypress open```

**Screenshots**
<img width="1597" alt="image" src="https://github.com/shivamguys/irctc-cypress-automation/assets/17222278/b040a740-61d1-4f80-921e-a365a7140b10">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : Chrome 
 - Version Version 124.0.6367.91 (Official Build) (arm64)

**Additional context**

**Comment by shivamguys** [comment]
I am not encountering any such issues did you tried again ? @jabir366

**Comment by jabir366** [comment]
Hi @shivamguys It was a mistake from my side, I was using the `username` and `password` keys in  the `cypress.env.json` without looking at the latest changes, now they are moved to `USERNAME` and `PASSWORD`.  I am closing this issue as it is resolved, Thanks!

**Comment by shivamguys** [comment]
Glad to know it's working...... @jabir366
