### ISSUE TITLE
The captcha solver fails during the time of tatkal booking

### ISSUE THREAD

**Issue by Ldoz13** [shivamguys/irctc-cypress-automation#47]
The captcha solver fails during the time of tatkal booking (rest of the time it works).  Website is throwing invalid captcha error. 
I am running the EasyOCR in CPU mode.

**Comment by shivamguys** [comment]
It succeeds after 3 or 4 attempts in worst case scenarios.

**Comment by Ldoz13** [comment]
> It succeeds after 3 or 4 attempts in worst case scenarios. 

Can we use another model to solve the captcha?

**Comment by ramchandra06032004** [comment]
solve captcha manually it takes less time, go to cypress.env.json and "MANUAL_CAPTCHA": true then captcha not get solve automatically

**Comment by shivamguys** [comment]
Did you booked any ticket using this @ramchandra06032004

**Comment by ramchandra06032004** [comment]
Yes today i booked ticket of tutari express from thane station to Kudal station

**Comment by shivamguys** [comment]
Can you share some insights on [discussion board](https://github.com/shivamguys/irctc-cypress-automation/discussions/5)  like time it took for you to book tickets and at what time you started like that.

Many people doubt 🧐 like has anyone booked with this or not , 😁😁😁😁
@ramchandra06032004

**Comment by ramchandra06032004** [comment]
Yes i can, I'll share today after reaching home, now I am in college.

**Comment by shivamguys** [comment]
No problem just letting you know

**Comment by Ldoz13** [comment]
> solve captcha manually it takes less time, go to cypress.env.json and "MANUAL_CAPTCHA": true then captcha not get solve automatically  

I wanted to use this headless, that's why I don't want to use manual captcha
