### ISSUE TITLE
not doing anything after this screen

### ISSUE THREAD

**Issue by aman71711** [shivamguys/irctc-cypress-automation#49]
The tool becomes unresponsive when the pop-up of the last transaction details appears on the screen, preventing it from performing operations effectively.
![Screenshot 2024-05-21 034742](https://github.com/shivamguys/irctc-cypress-automation/assets/84751863/36d508fb-1191-4120-baa0-20920af4c27d)

**Comment by shivamguys** [comment]
I know about this does this screen pop up every time or is it only once ?

**Comment by aman71711** [comment]
It appeared only once

**Comment by shivamguys** [comment]
In that case if it pop ups you can close that popup manually and thing would work normally

**Comment by shivamguys** [comment]
Fixed #54  
Fixed #49 
Fixed #51 
Fixed #53
 this as well as **the Last Transaction Status Popping out on screen** .....

# Do Checkout the latest code
