### ISSUE TITLE
This Screen Keep Coming

### ISSUE THREAD

**Issue by Shreesh-Coder** [shivamguys/irctc-cypress-automation#51]
**Describe the bug**
![image](https://github.com/shivamguys/irctc-cypress-automation/assets/53047244/94e233ea-2113-472b-9ec1-c88cbbb9f4df)
This Screen Keep coming during the tatkal booking.
**If you are encountering any error please run this**
```npx cypress run --record --key 967b25a7-e4dd-4b5b-a143-d799131b2d3b --headed```
this would record your run and can be seen here https://cloud.cypress.io/projects/wy3npb/runs
Please paste the link of the recorded run while creating any issues so that we can see whats going on with you.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by balu7979** [comment]
Same Error to me using Kali linux

**Comment by dhivalogu** [comment]
+1

**Comment by shivamguys** [comment]
Fixed #54  
Fixed #49 
Fixed #51 
Fixed #53
 this as well as **the Last Transaction Status Popping out on screen** .....

# Do Checkout the latest code

**Comment by dhivalogu** [comment]
Hi, Seems 51 is a different issue and not fixed in the latest code? 51 happens after clicking the book now button after selecting the coach. No changes related to this section in latest commit? Is #51 addressed @shivamguys?

**Comment by shivamguys** [comment]
Does this happens only during tatkal?

I have checked the code on normal sl booking

**Comment by shivamguys** [comment]
If this occurs then i have no control to fix this this is thrown by IRCTC even when booking normally as a human sometimes

**Comment by dhivalogu** [comment]
Yes , debugged multiple times. Happens only during SL tatkal time. Issue shouldn't be in the code if this is the case
