### ISSUE TITLE
Process stuck while clicking date on train selection page!!

### ISSUE THREAD

**Issue by hanisntsolo** [shivamguys/irctc-cypress-automation#53]
Just before the book now button the script isn't clicking the exact date of travel.

**Comment by Jino1219** [comment]
this issue you're faced right https://github.com/shivamguys/irctc-cypress-automation/discussions/54 ? @hanisntsolo 
CC : @shivamguys

**Comment by shivamguys** [comment]
Fixed #54  
Fixed #49 
Fixed #51 
Fixed #53
 this as well as **the Last Transaction Status Popping out on screen** .....

# Apology for extreme delays......................
# Life is not going as expected therefore was busy in some other things like finding jobs giving interviews still no luck unemployed for the past 6 months...

@hanisntsolo @Jino1219 

Checkout the latest code
