### ISSUE TITLE
How to change browser from google to edge/firefox in windows

### ISSUE THREAD

**Issue by 520rahul** [shivamguys/irctc-cypress-automation#65]
Hi i am quite new to technical world. Please explain where to change the browser and secondly for tatkal booking at how much before time we will have to run the repo so that ticket is booked and no logout error is pop up. And i tried today booking tatkal ticket the system responded so slow whether any issue in this repo and lastly one more thing for tatkal booking when to run this repo whether at exaclty 10 am or any specific time of 20 or 30 seconds before.

One more request to add option of "book only if confirm seats are alloted" and " book  if all seats are alloted in same coach"

**Comment by shivamguys** [comment]
Just add ` --browser chrome ` in that whole command
@520rahul

**Comment by 520rahul** [comment]
> Just add `--browser chrome` in that whole command @520rahul

Can u please elaborate if possible. That would be very nice of u

**Comment by shivamguys** [comment]
@520rahul  that has been added, but it dosent shows up in page that option while booking for some trains.... You can check

**Comment by shivamguys** [comment]
example ` npx cypress run --headed --no-exit --browser chrome`

@520rahul

**Comment by 520rahul** [comment]
@shivamguys please do something regarding general ticket where repo is booking waiting list tickets without checking it is not confirm seat still
