### ISSUE TITLE
NOT WORKING RECENTLY

### ISSUE THREAD

**Issue by Learner00100** [shivamguys/irctc-cypress-automation#66]
from today the code is not working, it worked previously.
kindly solve soon.

**Comment by 520rahul** [comment]
> from today the code is not working, it worked previously. kindly solve soon.

Yeh i also faced the same issue today. It went to the login sceeen but stuck at that even did not autfilled login credentials. It was working till yesterday but atoppwd working today suddenly

**Comment by shivamguys** [comment]
@520rahul @Learner00100  will see tomorrow whats going wrong

**Comment by shivamguys** [comment]
Can you guys tell me @520rahul @Learner00100  wether you booked a ticket recently with this or is this the first time you would try booking?

**Comment by 520rahul** [comment]
> Can you guys tell me @520rahul @Learner00100 wether you booked a ticket recently with this or is this the first time you would try booking?

I have tried several times tivket booking but not actually booked the ticket but all the time repo was workine fine but today after opeing irctc page it stucks there and nothing happens

**Comment by shivamguys** [comment]
Fixed check now and reopen this issue if its not working....

@520rahul @Learner00100

**Comment by 520rahul** [comment]
Just checked. Repo is working but 2 issues to be mentioned for your perusal:-

1. Repo is loading slowly from opening irctc website to login page
2. As i mentioned in earlier also in another issue that repo is booking ticket for waiting list seat in general category booking. Kindly check.  And thanks a ton foe this repo
