### ISSUE TITLE
Not able to do a login 

### ISSUE THREAD

**Issue by balajha** [shivamguys/irctc-cypress-automation#68]
Now ,  after entering the respective command user id and password is not being filled automatically. 
![Screenshot 2024-08-31 231132](https://github.com/user-attachments/assets/90baa16b-21de-4f6c-b41e-93a622ef7d80)

**Comment by balajha** [comment]
![Uploading Screenshot 2024-08-31 231310.png…]()

**Comment by balajha** [comment]
![Screenshot 2024-08-31 231310](https://github.com/user-attachments/assets/2f7248e8-9aa7-4596-a08b-136bf71f38b0)

**Comment by shivamguys** [comment]
Kindly use the latest code that has been fixed un the latest code @balajha
