### ISSUE TITLE
error in the async func

### ISSUE THREAD

**Issue by VidhyaVarshanyJS** [shivamguys/irctc-cypress-automation#7]
![image](https://github.com/shivamguys/irctc-cypress-automation/assets/76642252/63d2c21b-8d3e-408d-ae99-298a19e68fd2)

**Comment by shivamguys** [comment]
Is it cloned to the latest commit?

**Comment by VidhyaVarshanyJS** [comment]
Yes...
I changes takal parameter to false..will it work that way

**Comment by shivamguys** [comment]
Will have a look at it after Diwali @VidhyaVarshanyJS

**Comment by shivamguys** [comment]
But i am not encountering any errors, did you tried again after that?

**Comment by VidhyaVarshanyJS** [comment]
Yea...I am asking will it work for takal ,false parameter value

**Comment by shivamguys** [comment]
No tatkal=false would not book tatkal tickets , that would book normal
tickets

**Comment by shivamguys** [comment]
Fixed.......
