### ISSUE TITLE
Its better to use flask server for better captcha load

### ISSUE THREAD

**Issue by hanisntsolo** [shivamguys/irctc-cypress-automation#86]
While booking with direct call to app.py using exec is actually making the booking slow.
can make it much faster like less than 30 seconds with the help of flask server ontop of the language model to extract captcha.

Tested locally without flask server 1min 15 seconds 
With flask server < 30sec.

127.0.0.1 - - [19/Nov/2024 10:40:55] "←[37mPOST /extract-text HTTP/1.1←[0m" 200 - First
127.0.0.1 - - [19/Nov/2024 10:41:28] "←[37mPOST /extract-text HTTP/1.1←[0m" 200 - Last

**Comment by shivamguys** [comment]
> @shivamguys if I want to contribute what is the process?

Its much simple the only thing is it should be working 😁

**Comment by hanisntsolo** [comment]
PR Raised:
https://github.com/shivamguys/irctc-cypress-automation/pull/88

we can discuss more in this PR and I am happy to furnish edits on feedback.

**Comment by hanisntsolo** [comment]
you can checkout the PR run it on your local if it looks ok to you we can have it merged.

**Comment by shivamguys** [comment]
Closing this if any things pops up will discuss in PR
